export const REGISTRATION = 'REGISTRATION'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const INIT_USER = 'INIT_USER'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const IS_LOADING = 'IS_LOADING'
export const GET_CITY= 'GET_CITY'
